name: Samba
version: 4.18.5-5
slug: samba
description: Share paths as read only
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
watchdog: tcp://[HOST]:[PORT:445]
hassio_api: true
apparmor: true
ports:
  137/udp: 137
  139/tcp: 139
  445/tcp: 445
map:
  - share
options:
  shares: []
schema:
  shares:
    - match(^[A-Za-z0-9]+ /share/.+$)?
codenotary: passtschu@freenet.de
