name: Samba
version: 4.18.9-0
slug: samba
description: Share paths as read only
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
watchdog: tcp://[HOST]:[PORT:445]
hassio_api: true
apparmor: true
ports:
  137/udp: 137
  139/tcp: 139
  445/tcp: 445
map:
  - share:rw
options:
  users: []
  shares: []
schema:
  user: str?
  users:
    - username: str
      password: password
  shares:
    - name: str
      path: match(^/share/.*$)
      users: str?
      writable: bool?
codenotary: escoand@users.noreply.github.com
