build_from:
  aarch64: docker.io/matiasdelellis/facerecognition-external-model:v1
  amd64: docker.io/matiasdelellis/facerecognition-external-model:v1
codenotary:
  signer: escoand@users.noreply.github.com
