name: Nextcloud Facerecognition
version: 1.0.0-7
slug: nextcloud-facerecognition
description: Nextcloud Facerecognition External Model
arch:
  - aarch64
  - amd64
init: false
webui: http://[HOST]:[PORT:5000]/
apparmor: true
ports:
  5000/tcp: null
options:
  api_key: ""
  workers: 1
schema:
  api_key: str?
  workers: int?
codenotary: escoand@users.noreply.github.com
