build_from:
  aarch64: ghcr.io/immich-app/immich-machine-learning:v1.139.2
  amd64: ghcr.io/immich-app/immich-machine-learning:v1.139.2
  i386: ghcr.io/immich-app/immich-machine-learning:v1.139.2
codenotary:
  signer: escoand@users.noreply.github.com

