build_from:
  aarch64: ghcr.io/immich-app/immich-machine-learning:v1.129.0-armnn
  amd64: ghcr.io/immich-app/immich-machine-learning:v1.129.0
  i386: ghcr.io/immich-app/immich-machine-learning:v1.129.0
codenotary:
  signer: escoand@users.noreply.github.com

