build_from:
  aarch64: ghcr.io/immich-app/immich-machine-learning:v1.140.1
  amd64: ghcr.io/immich-app/immich-machine-learning:v1.140.1
  i386: ghcr.io/immich-app/immich-machine-learning:v1.140.1
codenotary:
  signer: escoand@users.noreply.github.com

