build_from:
  aarch64: ghcr.io/immich-app/immich-machine-learning:v1.135.1
  amd64: ghcr.io/immich-app/immich-machine-learning:v1.135.1-openvino
  i386: ghcr.io/immich-app/immich-machine-learning:v1.135.1-openvino
codenotary:
  signer: escoand@users.noreply.github.com

