build_from:
  aarch64: ghcr.io/immich-app/immich-machine-learning:v2.2.3
  amd64: ghcr.io/immich-app/immich-machine-learning:v2.2.3
  i386: ghcr.io/immich-app/immich-machine-learning:v2.2.3
codenotary:
  signer: escoand@users.noreply.github.com

