build_from:
  aarch64: ghcr.io/immich-app/immich-machine-learning:v1.135.3
  amd64: ghcr.io/immich-app/immich-machine-learning:v1.135.3-openvino
  i386: ghcr.io/immich-app/immich-machine-learning:v1.135.3-openvino
codenotary:
  signer: escoand@users.noreply.github.com

