build_from:
  aarch64: ghcr.io/immich-app/immich-machine-learning:v1.143.0
  amd64: ghcr.io/immich-app/immich-machine-learning:v1.143.0
  i386: ghcr.io/immich-app/immich-machine-learning:v1.143.0
codenotary:
  signer: escoand@users.noreply.github.com

