build_from:
  aarch64: ghcr.io/immich-app/immich-machine-learning:v1.134.0
  amd64: ghcr.io/immich-app/immich-machine-learning:v1.134.0-openvino
  i386: ghcr.io/immich-app/immich-machine-learning:v1.134.0-openvino
codenotary:
  signer: escoand@users.noreply.github.com

