build_from:
  aarch64: ghcr.io/immich-app/immich-machine-learning:v1.131.2
  amd64: ghcr.io/immich-app/immich-machine-learning:v1.131.2-openvino
  i386: ghcr.io/immich-app/immich-machine-learning:v1.131.2-openvino
codenotary:
  signer: escoand@users.noreply.github.com

