build_from:
  aarch64: ghcr.io/immich-app/immich-machine-learning:v1.139.4
  amd64: ghcr.io/immich-app/immich-machine-learning:v1.139.4
  i386: ghcr.io/immich-app/immich-machine-learning:v1.139.4
codenotary:
  signer: escoand@users.noreply.github.com

