build_from:
  aarch64: ghcr.io/immich-app/immich-machine-learning:v1.136.0
  amd64: ghcr.io/immich-app/immich-machine-learning:v1.136.0-cuda
  i386: ghcr.io/immich-app/immich-machine-learning:v1.136.0-cuda
codenotary:
  signer: escoand@users.noreply.github.com

