build_from:
  armhf: ghcr.io/immich-app/immich-machine-learning:v1.126.1-armnn
  armv7: ghcr.io/immich-app/immich-machine-learning:v1.126.1-armnn
  aarch64: ghcr.io/immich-app/immich-machine-learning:v1.126.1-armnn
  amd64: ghcr.io/immich-app/immich-machine-learning:v1.126.1
  i386: ghcr.io/immich-app/immich-machine-learning:v1.126.1
codenotary:
  signer: escoand@users.noreply.github.com

