build_from:
  armhf: ghcr.io/immich-app/immich-machine-learning:v1.127.0-armnn
  armv7: ghcr.io/immich-app/immich-machine-learning:v1.127.0-armnn
  aarch64: ghcr.io/immich-app/immich-machine-learning:v1.127.0-armnn
  amd64: ghcr.io/immich-app/immich-machine-learning:v1.127.0
  i386: ghcr.io/immich-app/immich-machine-learning:v1.127.0
codenotary:
  signer: escoand@users.noreply.github.com

