build_from:
  aarch64: ghcr.io/immich-app/immich-machine-learning:v1.137.3
  amd64: ghcr.io/immich-app/immich-machine-learning:v1.137.3-cuda
  i386: ghcr.io/immich-app/immich-machine-learning:v1.137.3-cuda
codenotary:
  signer: escoand@users.noreply.github.com

