name: Immich Machine Learning
# renovate: datasource=docker depName=ghcr.io/immich-app/immich-machine-learning
version: 1.140.1-0
slug: immich-ml
description: Self-hosted photo and video management solution
arch:
  - aarch64
  - amd64
  - i386
map:
  - type: addon_config
    path: /cache
    read_only: false
devices:
  - /dev/dri
init: false
apparmor: false
ports:
  3003/tcp: null
watchdog: http://[HOST]:3003/ping
codenotary: escoand@users.noreply.github.com

# we need --security-opt=systempaths=unconfined for RKNN support
# the devicetree option does it wrong, currently
# see https://github.com/blakeblackshear/frigate-hass-addons/issues/145
