build_from:
  armhf: docker.io/arm32v7/nextcloud:30.0.3
  armv7: docker.io/arm32v7/nextcloud:30.0.3
  aarch64: docker.io/arm64v8/nextcloud:30.0.3
  amd64: docker.io/amd64/nextcloud:30.0.3
  i386: docker.io/i386/nextcloud:30.0.3
codenotary:
  signer: escoand@users.noreply.github.com
