build_from:
  armhf: arm32v6/nextcloud:26.0.1
  armv7: arm32v7/nextcloud:26.0.1
  aarch64: arm64v8/nextcloud:26.0.1
  amd64: amd64/nextcloud:26.0.1
  i386: i386/nextcloud:26.0.1
codenotary:
  base_image: passtschu@freenet.de
  signer: passtschu@freenet.de
