build_from:
  armhf: arm32v6/nextcloud:27.0.0
  armv7: arm32v7/nextcloud:27.0.0
  aarch64: arm64v8/nextcloud:27.0.0
  amd64: amd64/nextcloud:27.0.0
  i386: i386/nextcloud:27.0.0
codenotary:
  base_image: passtschu@freenet.de
  signer: passtschu@freenet.de
