build_from:
  armhf: docker.io/arm32v7/nextcloud:32.0.2
  armv7: docker.io/arm32v7/nextcloud:32.0.2
  aarch64: docker.io/arm64v8/nextcloud:32.0.2
  amd64: docker.io/amd64/nextcloud:32.0.2
  i386: docker.io/i386/nextcloud:32.0.2
codenotary:
  signer: escoand@users.noreply.github.com
