build_from:
  armhf: docker.io/arm32v6/nextcloud:28.0.3
  armv7: docker.io/arm32v7/nextcloud:28.0.4
  aarch64: docker.io/arm64v8/nextcloud:28.0.4
  amd64: docker.io/amd64/nextcloud:28.0.4
  i386: docker.io/i386/nextcloud:28.0.4
codenotary:
  signer: escoand@users.noreply.github.com
