build_from:
  armhf: docker.io/arm32v6/nextcloud:27.0.0
  armv7: docker.io/arm32v7/nextcloud:27.0.0
  aarch64: docker.io/arm64v8/nextcloud:27.0.1
  amd64: docker.io/amd64/nextcloud:27.0.1
  i386: docker.io/i386/nextcloud:27.0.0
codenotary:
  signer: passtschu@freenet.de
