build_from:
  armhf: docker.io/arm32v7/nextcloud:31.0.9
  armv7: docker.io/arm32v7/nextcloud:31.0.9
  aarch64: docker.io/arm64v8/nextcloud:31.0.9
  amd64: docker.io/amd64/nextcloud:31.0.9
  i386: docker.io/i386/nextcloud:32.0.0
codenotary:
  signer: escoand@users.noreply.github.com
