build_from:
  armhf: arm32v6/nextcloud:26.0.2
  armv7: arm32v7/nextcloud:26.0.2
  aarch64: arm64v8/nextcloud:26.0.2
  amd64: amd64/nextcloud:26.0.2
  i386: i386/nextcloud:26.0.2
codenotary:
  base_image: passtschu@freenet.de
  signer: passtschu@freenet.de
