build_from:
  armhf: ghcr.io/home-assistant/armhf-base:3.19
  armv7: ghcr.io/home-assistant/armv7-base:3.19
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  amd64: ghcr.io/home-assistant/amd64-base:3.19
  i386: ghcr.io/home-assistant/i386-base:3.18
codenotary:
  base_image: notary@home-assistant.io
  signer: escoand@users.noreply.github.com
