build_from:
  armhf: ghcr.io/home-assistant/armv7-base:3.22
  armv7: ghcr.io/home-assistant/armv7-base:3.22
  aarch64: ghcr.io/home-assistant/aarch64-base:3.22
  amd64: ghcr.io/home-assistant/amd64-base:3.22
  i386: ghcr.io/home-assistant/i386-base:3.22
codenotary:
  base_image: notary@home-assistant.io
  signer: escoand@users.noreply.github.com
