name: MiniDLNA
# renovate: datasource=repology depName=alpine_3_21/minidlna versioning=loose
version: 1.3.3-2
slug: minidlna
description: Simple media server software, with the aim of being fully compliant with DLNA/UPnP-AV clients
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
webui: http://[HOST]:[PORT:8200]/
watchdog: http://[HOST]:[PORT:8200]/
hassio_api: true
apparmor: true
host_network: true
ports:
  8200/tcp: 8200
map:
  - share
options:
  media_dirs: []
schema:
  media_dirs:
    - match(^([APV],)?/share/.*)
  root_container: list(.|B|M|V|P)?
  user: int?
codenotary: escoand@users.noreply.github.com
