name: pgvecto.rs
version: 0.2.0-0
slug: pgvectors
description: Scalable Vector Search in Postgres
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
apparmor: true
watchdog: tcp://[HOST]:5432
map:
  - addon_config:rw
options:
  database_name: ""
  database_user: ""
  database_password: ""
schema:
  database_name: str?
  database_user: str?
  database_password: password?
codenotary: escoand@users.noreply.github.com

