name: Redis
version: 7.2.1-1
slug: redis
description: The open source in-memory data store
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
apparmor: true
init: false
watchdog: tcp://[HOST]:6379
