name: Mautrix Whatsapp
version: 0.10.5-1
slug: mautrix-whatsapp
description: ""
arch:
  - aarch64
  - amd64
init: false
watchdog: http://[HOST]:[PORT:29318]/_matrix/mau/ready
apparmor: true
ports:
  29318/tcp: null
map:
  - addon_config:rw
config:
  server_name: null
  server_url: http://local-synapse:8008
schema:
  server_name: str
  server_url: url
environment:
  GID: "991"
  UID: "991"
codenotary: escoand@users.noreply.github.com
